### ISSUE TITLE
news article and images on the right

### ISSUE THREAD

**Issue by uf0** [calibro/forccast-website#10]
The idea behind the 2 columns in the news section was to give more importance to the images.
For the majority of the posts the number of img/video was very limited (0-3) so the layout played very well in our opinion. 
Very few posts have more than 3 images and we agree with you that sometimes the user could be lost.

If, in the economy of the news section, you believe that the original position is more important probably the best option is to keep the images inside the text (like in the mobile layout) and not to keep them on the right column with some scrollspy behaviour which, in any case, do not guarantee to keep trace of original position when we have a lot of images. 

In our opinion you should choose one of 2 options:

1. keep the actual layout
2. use the mobile layout also on the desktop

**Comment by robindemourat** [comment]
Okay, let's keep the actual layout. I am not sure we understood each other concerning this question (our issue was not with the two-columns layout, but with the vertical alignment of the images with their point of insertion in the original text). Anyway it works pretty well like that for most of posts, now that images are legended. Good to close !
