### ISSUE TITLE
Project page : simple way to switch from institution tags to tags

### ISSUE THREAD

**Issue by robindemourat** [calibro/forccast-website#13]
In project page

When selecting an "institution" filter, I must uncheck it before I select another. Is that really necessary as we don't need to unite or filter projects with multiple filters, regarding the data ? Could the click on one institution filter uncheck the other ones ?

**Comment by uf0** [comment]
It could be done, but when you will have also the TAG you should re-adapt the code.
Furthermore we need to keep the possibility to uncheck or we need to add a reset button in order to remove the filter.
What do you think?

**Comment by robindemourat** [comment]
The feature requires complicated changes for this one regarding the gain and it will be less relevant with more data (tags, etc.) - let's let it as is for now and see if the issue persists.
