### ISSUE TITLE
Thumbnails for some news are not parsed

### ISSUE THREAD

**Issue by robindemourat** [calibro/forccast-website#28]
On the hypotheses blog:

<img width="1280" alt="capture d ecran 2017-06-07 a 18 08 27" src="https://user-images.githubusercontent.com/1876890/26888778-563845f0-4bac-11e7-8ff0-9710e77770a5.png">

( https://forccast.hypotheses.org/ )

On the website (it should not be grey) :

<img width="1280" alt="capture d ecran 2017-06-07 a 18 07 21" src="https://user-images.githubusercontent.com/1876890/26888724-3477353e-4bac-11e7-9827-32730822a5a1.png">

(url of the full post: http://controverses.org/fr/news/la-pr-servation-des-oc-ans-au-menu-d-une-simulation-europ-enne-pour-des-l-ves-du-secondaire/)

**Comment by uf0** [comment]
that's because when a post is featured it doesn't appear in the list below...and the actual scraper acts only on the posts list and not on the featured ones.
TODO: modify scraper
