### ISSUE TITLE
Static pages links --> set targets to blank

### ISSUE THREAD

**Issue by robindemourat** [calibro/forccast-website#29]

**Comment by uf0** [comment]
which pages? those two?
http://controverses.org/fr/what-is-forccast/
http://controverses.org/fr/controversies/

target blank should be set also on internal link?

**Comment by robindemourat** [comment]
> which pages? those two?
http://controverses.org/fr/what-is-forccast/
http://controverses.org/fr/controversies/

Yes it is on these ones !

> target blank should be set also on internal link?

Ideally it should not, but it's not a big deal if internal links also open in blank pages.
