### ISSUE TITLE
left menu style

### ISSUE THREAD

**Issue by uf0** [calibro/forccast-website#8]
From a UI point of view we don't like very much the red underline on the left menu. We think that a nav menu element should differs from a _classical_ link
Please have a look to this proposal -> http://calib.ro/forccast-website/

otherwise here an image with your proposal
<img width="1082" alt="screen shot 2017-04-27 at 12 34 50" src="https://cloud.githubusercontent.com/assets/1922342/25493443/80b2ed54-2b76-11e7-90e1-28d80784fcf5.png">

of course the last word is on you :)

**Comment by robindemourat** [comment]
Okay, sorry the email was not clear about this, by aside we meant the right column with the side notes.

In the following snapshot the second sidenote contains a link, it is not signaled as a link :

![capture du 2017-04-27 18-59-27](https://cloud.githubusercontent.com/assets/1876890/25494963/c9ad5a1c-2b7b-11e7-8d6a-0afa3d4ebeca.png)

And it's only when hovering the link that it becomes underlined :

![capture du 2017-04-27 18-59-38](https://cloud.githubusercontent.com/assets/1876890/25494962/c9ac647c-2b7b-11e7-8351-a87baaee1aa7.png)

=> so users can't know it's a link until they hover it - could you style it the same way as in the body text ?
