### ISSUE TITLE
subtitle

### ISSUE THREAD

**Issue by uf0** [calibro/forccast-website#9]
Since the layout is fluid, it's quite difficult to control line breaking and keep _cartographie des controverses_ on the same line.
One solution is to use and image for the subtitle.

What do you think?

**Comment by robindemourat** [comment]
Yes it is an option - maybe another one is to add `<br/>` tags before and after  "cartographie des controverses" and let it split when there's no room for it  - the main concern from Nicolas was that it was not necessarily understandable as the explanation of the acronym

**Comment by uf0** [comment]
Ok, we already use some `<br/>` tag, so I tried to refine a bit the behaviour with some media queries.
Furthermore I changed to uppercase the initial of the acronym in order to highlight them.

Here the result on the most used screen resolutions:
<img width="770" alt="screen shot 2017-04-28 at 11 24 00" src="https://cloud.githubusercontent.com/assets/1922342/25523218/2390aa68-2c06-11e7-87c1-ebd4008c5836.png">

<img width="1089" alt="screen shot 2017-04-28 at 11 24 15" src="https://cloud.githubusercontent.com/assets/1922342/25523232/2db83e52-2c06-11e7-8d10-bd5195df60a7.png">

<img width="1082" alt="screen shot 2017-04-28 at 11 24 27" src="https://cloud.githubusercontent.com/assets/1922342/25523236/33263b1e-2c06-11e7-996d-244de4b3bd0c.png">

![screen shot 2017-04-28 at 11 24 38](https://cloud.githubusercontent.com/assets/1922342/25523239/37c89004-2c06-11e7-9a12-867c5fa64de4.png)

**Comment by robindemourat** [comment]
Thanks, this last solution is good for us.
